### PR TITLE
Improve installation instructions in the README

### LINKED ISSUE #4: Mix deps.get can't fetch the library
I am running Elixir 1.3.1 and it gave me the following error message: `error: pathspec 'origin/master' did not match any file(s) known to git.`

I believe it is because the master branch has been deleted and replaced with develop.

### PR DESCRIPTION
**Pull request by zoldar**
Closes #4 

Just in case, the rationale behind step 2. is laid out here:

http://blog.plataformatec.com.br/2016/07/understanding-deps-and-applications-in-your-mixfile/

\cc @josemrb @tomekowal @wojtekmach

### CODE REVIEW

**Comment by tomekowal** [comment]
Fully agree.

**Comment by aerosol** [comment]
tsk tsk I'd just push to hex

**Comment by wojtekmach** [comment]
I think pushing this to hex is fine, but I'd really like us to solve slow & memory hungry compilation first though.

**Comment by aerosol** [comment]
@wojtekmach the only way I can think of rn is to binary-cache metadata generated on the fly (`erlang:term_to_binary/1`)

**Pull request merged**
