### PR TITLE
Update PhoneNumberMetadata to be more recent

### PR DESCRIPTION
**Pull request by tburraston**
Some minor updates to support new area codes.

Thanks!

### CODE REVIEW

**Comment by szymon-jez** [comment]
This is related to https://github.com/socialpaymentsbv/ex_phone_number/issues/39. @josemrb Do you still plan doing the upgrade?

**Comment by josemrb** [comment]
> Some minor updates to support new area codes.

Sorry, you can't update the XML file without updating the code.

**Comment by josemrb** [comment]
> This is related to #39. @josemrb Do you still plan doing the upgrade?

Yes, but there are still several tests that are failing.

I'll create an issue with more information on this in the next few days.

**Comment by szymon-jez** [comment]
@josemrb Maybe we should first just do the patch upgrade you have suggested here https://github.com/socialpaymentsbv/ex_phone_number/pull/33#issuecomment-565619362 and then pursue the minor/major upgrades?

**Comment by josemrb** [comment]
@szymon-jez that was the first thing I tried but I ran into other problems.
There are parts of the code that were not updated correctly in the past and it is necessary to review the whole project.
Now I'm trying to update to the latest version.

**Comment by tburraston** [comment]
Hey @josemrb,
I don't mean to be a thorn in your side, but do you happen to have an estimate on when you think you'll be able to release an update? Is there anything I might be able to help with; I'd gladly do what I can.

**Pull request closed without merging**
